-- Polaris Roleplay Tables Migration
-- Created on 2026-08-04

CREATE TABLE `rp_users` (
  `id` int(11) NOT NULL,
  `level` int(11) NOT NULL DEFAULT 1,
  `level_exp` int(11) NOT NULL DEFAULT 0,
  `class` varchar(100) NOT NULL DEFAULT '',
  `permanent_class` enum('0','1') NOT NULL DEFAULT '0',
  `job_id` int(11) NOT NULL DEFAULT 1,
  `job_rank` int(11) NOT NULL DEFAULT 1,
  `job_request` int(11) NOT NULL DEFAULT 0,
  `sendhome_time_left` int(11) NOT NULL DEFAULT 0,
  `maxhealth` int(11) NOT NULL DEFAULT 100,
  `curhealth` int(11) NOT NULL DEFAULT 100,
  `maxenergy` int(11) NOT NULL DEFAULT 100,
  `curenergy` int(11) NOT NULL DEFAULT 100,
  `curalcohol` int(11) NOT NULL DEFAULT 0,
  `maxalcohol` int(11) NOT NULL DEFAULT 100,
  `kevlar` int(11) NOT NULL DEFAULT 0,
  `hunger` int(11) NOT NULL DEFAULT 0,
  `sida` int(11) NOT NULL DEFAULT 0,
  `hygiene` int(11) NOT NULL DEFAULT 0,
  `animo` int(11) NOT NULL DEFAULT 100,
  `poop` int(11) NOT NULL DEFAULT 0,
  `intelligence` int(11) NOT NULL DEFAULT 0,
  `strength` int(11) NOT NULL DEFAULT 0,
  `stamina` int(11) NOT NULL DEFAULT 0,
  `intelligence_exp` int(11) NOT NULL DEFAULT 0,
  `strength_exp` int(11) NOT NULL DEFAULT 0,
  `stamina_exp` int(11) NOT NULL DEFAULT 0,
  `passive_mode` enum('0','1') NOT NULL DEFAULT '0',
  `is_stun` enum('0','1') NOT NULL DEFAULT '0',
  `is_dead` enum('0','1') NOT NULL DEFAULT '0',
  `dead_time_left` int(11) NOT NULL DEFAULT 0,
  `is_jailed` enum('0','1') NOT NULL DEFAULT '0',
  `jailed_time_left` int(11) NOT NULL DEFAULT 0,
  `is_wanted` enum('0','1') NOT NULL DEFAULT '0',
  `wanted_level` int(11) NOT NULL DEFAULT 0,
  `wanted_time_left` int(11) NOT NULL DEFAULT 0,
  `on_probation` enum('0','1') NOT NULL DEFAULT '0',
  `probation_time_left` int(11) NOT NULL DEFAULT 0,
  `is_cuffed` enum('0','1') NOT NULL DEFAULT '0',
  `cuffed_time_left` int(11) NOT NULL DEFAULT 0,
  `punches` int(11) NOT NULL DEFAULT 0,
  `kills` int(11) NOT NULL DEFAULT 0,
  `hit_kills` int(11) NOT NULL DEFAULT 0,
  `gun_kills` int(11) NOT NULL DEFAULT 0,
  `deaths` int(11) NOT NULL DEFAULT 0,
  `cop_deaths` int(11) NOT NULL DEFAULT 0,
  `time_worked` int(11) NOT NULL DEFAULT 0,
  `arrests` int(11) NOT NULL DEFAULT 0,
  `arrested` int(11) NOT NULL DEFAULT 0,
  `evasions` int(11) NOT NULL DEFAULT 0,
  `bank_account` int(11) NOT NULL DEFAULT 0,
  `bank_target` int(11) NOT NULL DEFAULT 0,
  `bank_chequings` int(11) NOT NULL DEFAULT 0,
  `bank_savings` int(11) NOT NULL DEFAULT 0,
  `weedbaul` int(11) NOT NULL DEFAULT 0,
  `BasuLvl` int(11) NOT NULL DEFAULT 1,
  `BasuXP` int(11) NOT NULL DEFAULT 0,
  `hunt_points` int(11) NOT NULL DEFAULT 0,
  `hunt_skins` varchar(255) NOT NULL DEFAULT '',
  `ArmLvl` int(11) NOT NULL DEFAULT 1,
  `ArmXP` int(11) NOT NULL DEFAULT 0,
  `MecLvl` int(11) NOT NULL DEFAULT 1,
  `MecXP` int(11) NOT NULL DEFAULT 0,
  `CamLvl` int(11) NOT NULL DEFAULT 1,
  `CamXP` int(11) NOT NULL DEFAULT 0,
  `last_killed` int(11) NOT NULL DEFAULT 0,
  `married_to` int(11) NOT NULL DEFAULT 0,
  `hijo` int(11) NOT NULL DEFAULT 0,
  `gang_id` int(11) NOT NULL DEFAULT 0,
  `gang_rank` int(11) NOT NULL DEFAULT 0,
  `gang_request` int(11) NOT NULL DEFAULT 0,
  `changename_count` int(11) NOT NULL DEFAULT 0,
  `car` int(11) NOT NULL DEFAULT 0,
  `car_fuel` int(11) NOT NULL DEFAULT 0,
  `weed` int(11) NOT NULL DEFAULT 0,
  `cocaine` int(11) NOT NULL DEFAULT 0,
  `botiquin` int(11) NOT NULL DEFAULT 0,
  `heroina` int(11) NOT NULL DEFAULT 0,
  `caramelos` int(11) NOT NULL DEFAULT 0,
  `medicina` int(11) NOT NULL DEFAULT 0,
  `cigarette` int(11) NOT NULL DEFAULT 0,
  `pildora` int(11) NOT NULL DEFAULT 0,
  `dynamite` int(11) NOT NULL DEFAULT 0,
  `weedmateria` int(11) NOT NULL DEFAULT 0,
  `unlocked_quests` varchar(255) NOT NULL DEFAULT '',
  `brawl_wins` int(11) NOT NULL DEFAULT 0,
  `cw_wins` int(11) NOT NULL DEFAULT 0,
  `mw_wins` int(11) NOT NULL DEFAULT 0,
  `soloqueue_wins` int(11) NOT NULL DEFAULT 0,
  `is_noob` enum('0','1') NOT NULL DEFAULT '1',
  `noob_time_left` int(11) NOT NULL DEFAULT 0,
  `inmunidad_activada` enum('0','1') NOT NULL DEFAULT '0',
  `vip_banned` int(11) NOT NULL DEFAULT 0,
  `last_coordinates` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rp_products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `display_name` varchar(255) NOT NULL,
  `price` int(11) NOT NULL DEFAULT 0,
  `type` varchar(255) NOT NULL,
  `can_stack` enum('0','1') NOT NULL DEFAULT '0',
  `max_cant` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_unique` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rp_user_products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `extradata` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_user_id` (`user_id`),
  KEY `fk_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rp_cooldowns` (
  `id` int(11) NOT NULL,
  `robbery` int(11) NOT NULL DEFAULT 0,
  `text_cooldown` int(11) NOT NULL DEFAULT 0,
  `robbery_bank` int(11) NOT NULL DEFAULT 0,
  `medipacks` int(11) NOT NULL DEFAULT 0,
  `psvmode` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
